#!/bin/bash

echo "==================================="
echo "Agent Validator Test Script"
echo "==================================="
echo ""

echo "This script will help you test the agent validation plugin."
echo ""
echo "In your OpenCode CLI, run these commands one by one:"
echo ""
echo "1. debug_validator"
echo "   └─ Check if 'agent' field shows real agent names"
echo ""
echo "2. analyze_agent_usage"
echo "   └─ See which agents were active and their tool usage"
echo ""
echo "3. analyze_context_reads"
echo "   └─ View context files that were loaded"
echo ""
echo "4. validate_session"
echo "   └─ Full compliance and tracking report"
echo ""
echo "5. check_context_compliance"
echo "   └─ Verify context loading rules were followed"
echo ""
echo "==================================="
echo ""
echo "What to look for:"
echo "✓ Agent names should NOT be 'unknown'"
echo "✓ Should see 'openagent' and potentially 'general' subagent"
echo "✓ Context file 'standards/code.md' should be tracked"
echo "✓ Tools should be attributed to correct agents"
echo ""
